### ISSUE TITLE
Possible API footgun by Context being Copy

### ISSUE THREAD

**Issue by vorner** [stainless-steel/md5#15]
Hello

While it might be my own gut feeling, I think the `Context` shouldn't be `Copy`. Copying happens automatically and invisibly, which is fine with value-style types (eg. references, numbers, etc). However, copying a context without knowing it might create some hard to find bugs (eg. why does the digest turn out to be different?).

For example, this code produces two different hashes and it is not clearly visible that the code is wrong.

```rust
extern crate md5;

use std::cell::RefCell;

use md5::Context;

fn update(context: &RefCell<Option<Context>>) {
    let borrow = context.borrow_mut();
    if let Some(mut context) = *borrow {
        context.consume("Hello");
    }
}

fn main() {
    let context = RefCell::new(Some(Context::new()));
    update(&context);
    println!("{:x}", context.borrow_mut().unwrap().compute());
    println!("{:x}", md5::compute("Hello"));
}
```

May I suggest removing the `Copy` implementation from `Context` (it is fine on `Digest` ‒ making copy of that one won't, do anything bad, but „branching“ the computation on accidental copy is something I don't usually want). I think most code doesn't make copies of the context and if so, it is still more readable with explicit `.clone()`.

**Comment by IvanUkhov** [comment]
Thank you for brining this up! I think it’s a valid point.

Let us take a moment and think about potential downsides.

**Comment by vorner** [comment]
OK, here are few:

* It's certainly a semver-incompatible change.
* It probably might make some uses less ergonomic, though I don't have a concrete example.
* Some places might actually mandate `Copy` types ‒ like https://doc.rust-lang.org/std/cell/struct.Cell.html#method.get. Again, I don't have a concrete example of useful use of these together, only a possibility.

**Comment by IvanUkhov** [comment]
Thank you!
