### ISSUE TITLE
0.6 tests are failing on 32bit

### ISSUE THREAD

**Issue by igor-raits** [stainless-steel/md5#17]
```rust
error: this expression will panic at runtime
   --> src/lib.rs:408:28
    |
408 |         let data = vec![0; MAX as usize + 1];
    |                            ^^^^^^^^^^^^^^^^ attempt to add with overflow
    |
    = note: #[deny(const_err)] on by default
```

**Comment by IvanUkhov** [comment]
Thanks for reporting this! This test is only relevant for 64-bit platforms. Would you be able to run what’s on master right now?

**Comment by igor-raits** [comment]
seems to be good, thanks!

**Comment by igor-raits** [comment]
@IvanUkhov just one thing, could you release 0.6.1 with this fix, please?

**Comment by IvanUkhov** [comment]
Done.

**Comment by igor-raits** [comment]
Awesome! Already [building in Fedora](https://koji.fedoraproject.org/koji/taskinfo?taskID=31464354).

Thanks for cooperation!
