### ISSUE TITLE
Tests never finish

### ISSUE THREAD

**Issue by kpcyrd** [stainless-steel/md5#18]
hello!

it seems the tests are stuck somehow:
```
running 4 tests
test tests::index ... ok
test tests::compute ... ok
test tests::overflow_count ... test tests::overflow_count has been running for over 60 seconds
test tests::overflow_length ... test tests::overflow_length has been running for over 60 seconds
test tests::overflow_count ... ok
```
do they just run for a very long time or is something broken?

**Comment by IvanUkhov** [comment]
Yes, some take a very long time to finish.

**Comment by IvanUkhov** [comment]
Take a look [here](https://travis-ci.org/stainless-steel/md5), for instance. However, it should be done in a few minutes, depending on the machine.
