### ISSUE TITLE
32bit arithmetic comments

### ISSUE THREAD

**Issue by tomhamiltonlambda** [stainless-steel/md5#20]
The Rust implementation is based off of the original paper, which included a C implementation: https://www.ietf.org/rfc/rfc1321.txt.

The paper was written in 1992, a time before 64 bit registers were widely available. The C code therefore splits the length of the message into two u32s, which then have manual arithmetic performed on them. The original source code includes comments around this arithmetic which have been omitted from the Rust implementation.

This issue is to help anyone who might be reading the code: 

```
let mut k = ((count[0] >> 3) & 0x3f) as usize;
let length = data.len() as u32;
count[0] = count[0].wrapping_add(length << 3);
if count[0] < length << 3 {
    count[1] = count[1].wrapping_add(1);
}
count[1] = count[1].wrapping_add(length >> 29);
```

and wondering what's going on.

The following comments should help future readers unfamiliar with this kind of arithmetic.

1. count[0] and count[1] represent the number of _bits_ of the input message in little-endian form (i.e. the memory layout of the little-endian 64bit number would be [count[0],count[1]]).
2. Bit shifts by 3 are used to transform this figure between a bytes count and a bits count.
3. The first line is computing the number of bytes modulo 64: first turn bits to bytes, then AND with 0x3f (63 in decimal) returns the number of bytes mod-64.
4. The first wrapping_add line is adding the length of the next chunk of message (in bits). If adding this extra length triggers a wrap (i.e. count[0] + length<<3 > 2^32-1 then we need to carry the add through to the upper 32 bit number (which is what the count[1].wrapping_add(1) is doing). wrapping_add is used here to take into account that the size of these numbers could be going above 64 bits in total.
5. Finally the last line is adding on the top-3 most significant bits from the original length to the count[1]. These weren't included when length << 3 was added to count[0] as they got chopped off by the left-shift.

Final note: given that we now have 64 bit integers freely available, this code could all be changed to u64.wrapping_add() style code. MD5 has been deprecated though, so there's little point.

**Comment by IvanUkhov** [comment]
Hello, thank you for the note! I agree that there are more direct and clearer ways now to perform that operation. If you have time and desire, please feel free to update and open a PR for review.

**Comment by tomhamiltonlambda** [comment]
Thanks for the reply. I've got a PR ready now, but I don't have permissions to push my branch to your repo. Please advise on how I can raise a PR.

**Comment by IvanUkhov** [comment]
You need to fork the repository first (via the Fork button on the main page) so you get a copy under your account. Then you push to your copy, and GitHub will then offer to open a PR to the original repository.
